### ISSUE TITLE
Stop executors cleanly instead of deleting their running pods

### ISSUE THREAD

**Issue by hustcat** [apache-spark-on-k8s/spark#204] opened 2017-03-27 07:49 UTC
[KubernetesClusterSchedulerBackend::stop](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala#L137) call K8S API server to delete excutor pod, then [send StopExector](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala#L151) to excutor process, this will make executor exit unfriendly:

```sh
2017-03-27 03:11:05 INFO  Executor:54 - Running task 1.0 in stage 0.0 (TID 1)
2017-03-27 03:11:05 INFO  Executor:54 - Finished task 1.0 in stage 0.0 (TID 1). 1041 bytes result sent to driver
2017-03-27 03:11:05 ERROR CoarseGrainedExecutorBackend:43 - RECEIVED SIGNAL TERM
2017-03-27 03:11:05 INFO  DiskBlockManager:54 - Shutdown hook called
2017-03-27 03:11:05 INFO  ShutdownHookManager:54 - Shutdown hook called
```

**Comment by ash211** [comment] 2017-03-27 16:45
@hustcat is this a duplicate of https://github.com/apache-spark-on-k8s/spark/issues/125 ?  The intention of that ticket (to preserve logs by allowing pods to complete vs deleting them) was different than this one but the change might be the same.

**Comment by foxish** [comment] 2017-03-27 18:17
These two issues seem orthogonal to me. We should be stopping executors gracefully and then deleting the executor pod (with an option to retain it for debugging purposes as described in #125.)

**Comment by hustcat** [comment] 2017-03-28 02:11
Yeah, @foxish 's idea is great!

**Comment by ash211** [comment] 2017-04-12 06:56
Opened a small PR up at #231 -- is that what you were thinking @hustcat ?

**Closed as completed** 2017-04-13 00:30 UTC

**Comment by hustcat** [comment] 2017-04-17 01:59
Yeah, this is exactly what I want, thanks @ash211
